# Generated by Django 3.2.7 on 2021-11-23 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iddoctor', models.CharField(max_length=10)),
                ('nombre_doctor', models.CharField(max_length=100)),
                ('profesion', models.CharField(max_length=50)),
                ('apodo', models.CharField(max_length=50)),
                ('rut_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eval03.paciente')),
            ],
        ),
    ]
